apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dnstools
spec:
  template:
    metadata:
      labels:
        dnstools: dnstools
    spec:
      nodeSelector:
        dnstools: dnstools-node
      containers:
        - name: dnstools
          image: tutum/dnsutils
          command:
          - bin/sleep
          - infinity
#oc label node worker-1.ocp43.local dnstools=dnstools-node
#oc label node worker-2.ocp43.local dnstools=dnstools-node          
