#echo -n 'admin' | base64
#You will get the encoded password: YWRtaW4=
#Create a secret.yml file for MySQL and Wordpress that will be mapped as an Environment Variable as follows:
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: YWRtaW4=
