kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: marcsc
