apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/desired-replicas: "1"
    openshift.io/deployer-pod.completed-at: 2020-03-14 00:51:04 +0000 UTC
    openshift.io/deployer-pod.created-at: 2020-03-13 23:50:54 +0000 UTC
    openshift.io/deployer-pod.name: fruits-catalog-1-deploy
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: fruits-catalog
    openshift.io/deployment.phase: Failed
    openshift.io/deployment.replicas: "0"
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"fruits-catalog","namespace":"fruits-catalog","selfLink":"/apis/apps.openshift.io/v1/namespaces/fruits-catalog/deploymentconfigs/fruits-catalog","uid":"c189caff-36ae-4844-807d-87b8a890ae53","resourceVersion":"25262025","generation":1,"creationTimestamp":"2020-03-13T23:50:53Z","labels":{"app":"fruits-catalog","group":"com.github.lbroudoux.msa","provider":"fabric8","version":"1.0.0-SNAPSHOT"},"annotations":{"fabric8.io/git-branch":"master","fabric8.io/git-commit":"a962fc98b1f8b0832fd9dd7e62b365c36217e6cd","fabric8.io/git-url":"https://github.com/lbroudoux/secured-fruits-catalog-k8s.git"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":3600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":2,"test":false,"selector":{"app":"fruits-catalog","group":"com.github.lbroudoux.msa","provider":"fabric8"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"fruits-catalog","group":"com.github.lbroudoux.msa","provider":"fabric8","version":"1.0.0-SNAPSHOT"},"annotations":{"fabric8.io/git-branch":"master","fabric8.io/git-commit":"a962fc98b1f8b0832fd9dd7e62b365c36217e6cd","fabric8.io/git-url":"https://github.com/lbroudoux/secured-fruits-catalog-k8s.git"}},"spec":{"containers":[{"name":"spring-boot","image":"fruits-catalog:latest","ports":[{"name":"http","containerPort":8080,"protocol":"TCP"},{"name":"prometheus","containerPort":9779,"protocol":"TCP"},{"name":"jolokia","containerPort":8778,"protocol":"TCP"}],"env":[{"name":"SPRING_DATA_MONGODB_URI","value":"mongodb://${SPRING_DATA_MONGODB_USER}:${SPRING_DATA_MONGODB_PASSWORD}@mongodb/sampledb"},{"name":"SPRING_DATA_MONGODB_USER","valueFrom":{"secretKeyRef":{"name":"mongodb","key":"database-user"}}},{"name":"SPRING_DATA_MONGODB_PASSWORD","valueFrom":{"secretKeyRef":{"name":"mongodb","key":"database-password"}}},{"name":"KUBERNETES_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"resources":{"limits":{"cpu":"1","memory":"256Mi"},"requests":{"cpu":"200m","memory":"256Mi"}},"livenessProbe":{"httpGet":{"path":"/actuator/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":15,"timeoutSeconds":3,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"readinessProbe":{"httpGet":{"path":"/actuator/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":15,"timeoutSeconds":3,"periodSeconds":10,"successThreshold":1,"failureThreshold":3},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":false}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":0,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]}}}
  creationTimestamp: "2020-03-13T23:50:53Z"
  generation: 7
  labels:
    app: fruits-catalog
    group: com.github.lbroudoux.msa
    openshift.io/deployment-config.name: fruits-catalog
    provider: fabric8
    version: 1.0.0-SNAPSHOT
  name: fruits-catalog-1
  namespace: fruits-catalog
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: fruits-catalog
    uid: c189caff-36ae-4844-807d-87b8a890ae53
  resourceVersion: "25480532"
  selfLink: /api/v1/namespaces/fruits-catalog/replicationcontrollers/fruits-catalog-1
  uid: e12183ed-5de2-4f85-b2e6-8152f759d535
spec:
  replicas: 1
  selector:
    app: fruits-catalog
    deployment: fruits-catalog-1
    deploymentconfig: fruits-catalog
    group: com.github.lbroudoux.msa
    provider: fabric8
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: master
        fabric8.io/git-commit: a962fc98b1f8b0832fd9dd7e62b365c36217e6cd
        fabric8.io/git-url: https://github.com/lbroudoux/secured-fruits-catalog-k8s.git
        openshift.io/deployment-config.latest-version: "1"
        openshift.io/deployment-config.name: fruits-catalog
        openshift.io/deployment.name: fruits-catalog-1
      creationTimestamp: null
      labels:
        app: fruits-catalog
        deployment: fruits-catalog-1
        deploymentconfig: fruits-catalog
        group: com.github.lbroudoux.msa
        provider: fabric8
        version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://${SPRING_DATA_MONGODB_USER}:${SPRING_DATA_MONGODB_PASSWORD}@mongodb/sampledb
        - name: SPRING_DATA_MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mongodb
        - name: SPRING_DATA_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mongodb
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: image-registry.openshift-image-registry.svc:5000/fruits-catalog/fruits-catalog@sha256:685f06e1924f0bd9e767596e6fc8470082f3ae55718b24574dc939a3863d1b93
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
