apiVersion: v1
kind: Secret
metadata:
  name: quaysecret
  annotations:
          tekton.dev/docker-0: https://quay.io 
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <encrypted password fron https://quay.io/user/<user>?tab=settings>
